### PR TITLE
Fixes for 967 and 969

### LINKED ISSUE #967: Glyph charts need to be updated for openqueue glyphs

### PR DESCRIPTION
**Pull request by henryso**
This pull request fixes #967 and—assuming that openqueue rules should be followed by oriscus scapus and virga reversa (in addition to virga)—#969.

All current tests pass, and I added tests to demonstrate the fix for #969.

Please review and merge if satisfactory.

### CODE REVIEW

File: src/gregoriotex/gregoriotex-write.c [hunk 1]
```diff
@@ -537,13 +537,27 @@ static const char *fusible_queued_shape(const gregorio_note *const note,
             name = ambitus_one? base_shape : longqueue_shape;
             break;
         }
-    } else {
+    } else if (glyph->u.notes.fuse_to_next_glyph) {
+        // TODO (5.0?) handle queue size on upwards fusion
```
Comment (eroux) [inline src/gregoriotex/gregoriotex-write.c]: Sorry, I didn't spot it first, but there's a C++ style comment here

**Comment by henryso** [comment]
Thanks, I'll fix it.
