### PR TITLE
Applied the lazy-load workaround for compatibility with luaotfload 2.6.

### LINKED ISSUE #734: GregorioNabcRef won't compile
In preparing the 4.0.1 release I noticed that GregorioNabcRef won't compile.  I'm getting the following error:

```
./veni-4_0_0.gtex:196: Undefined control sequence.
l.1 ...pace\hskip \gre@skip@nabcinterelementspaceERR
                                                  
l.196 }
```
The "ERR" at the end indicates to me a variable that isn't getting resolved correctly when writing the gtex file.  Can some one with more knowledge of the nabc system look into this and figure out what the problem is?

### PR DESCRIPTION
**Pull request by henryso**
Fixes #734.

This is the same fix as #717 applied to gregoriotex-nabc.lua.

I tested it on TeX Live 2015 with both luaotfload 2.5 and 2.6, and it works fine.  All tests pass.

Please review and merge if satisfactory.

### CODE REVIEW

File: tex/gregoriotex-nabc.lua [hunk 1]
```diff
@@ -71,6 +71,15 @@ local function gregallreadfont(font_id)
   local tab = {}
   local metrics = {}
   local fontdata = fonts.hashes.identifiers[font_id]
```
Comment (eroux) [inline tex/gregoriotex-nabc.lua]: I think it would be good to use `font.getfont` instead of accessing `fonts.hashes.identifiers`, as suggested in [this commit](https://github.com/phi-gamma/gregorio/commit/392e77a0c3c80e6da2d633ba3cc560b03644fa2a)

**Comment by eroux** [comment]
apart from my comment, ok for me to merge

**Comment by eroux** [comment]
see [this PR](https://github.com/henryso/gregorio/pull/7) for a fix

**Comment by henryso** [comment]
This works under 2.5 as well.  I wasn't sure that `fonts.hashes.identifiers[id]` produced the same thing as `font.getfont(id)`.  Merging.
